language: python
python:
- '3.6'
branches:
  only:
  - master
services:
- docker
sudo: required
before_install:
- make travis_up
script:
- make travis_test
- make travis_pii_check
after_success:
- pip install -U codecov
- docker exec notes /edx/app/notes/notes/.travis/run_coverage.sh
- codecov
env:
  matrix:
  - DOCKER_USERNAME=edxbuilder
  global:
    # encrypted DOCKER_PASSWORD
    secure: OgsQf8hp40s+E2btyl+RHcdgjqx9gZ4phlvm2tQ8Oy9mCO6hAy2XCjL1m2bidaFzwSjZXDZ7BhjD3yXpW2B+zP/yJNVKmdPA5E+D7YgFPdlOv7Wb+t0Z083Wbwqk7ZZgxLCcMLWf5vTs/QkPVAXbU8wJvQQC2l0EKESFnYkzNAI=
deploy:
  provider: script
  script: make docker_push
  on:
    branch: master
