language: python

python:
    - "3.6"

branches:
  only:
    - master

services:
  - docker

sudo: required

before_install:
    - make travis_up

script:
    - make travis_test
    - make travis_pii_check

after_success:
    - pip install -U codecov
    - docker exec notes /edx/app/notes/notes/.travis/run_coverage.sh
    - codecov

deploy:
  provider: script
  script: make docker_push
  on:
    branch: master

