language: python
python: 
- 2.7
- 3.5
sudo: false

install:
    - scripts/travis/install.sh
    - scripts/travis/setup.sh
    - pip install -r requirements/test.txt
    - git fetch origin master:refs/remotes/origin/master # https://github.com/edx/diff-cover#troubleshooting
    - pip install coveralls

script:
    - make validate

after_success:
    - coveralls

env:
- ESVER=-
- ESVER=0.90.11
- ESVER=1.4.2
