version: "2"

services:
  db:
    image: mysql:5.6.45
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "notes001"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "edx_notes_api"
  es:
    image: elasticsearch:1.5.2
    container_name: es
  notes:
    image: openedx/edx-notes-api:latest

    # Uncomment the next two lines to build from a local configuration repo
    # build: ../configuration/docker/build/discovery/

    container_name: edx_notes_api
    volumes:
      - ..:/edx/app/notes
    command: tail -f /dev/null
    depends_on:
      - "db"
      - "es"
    environment:
      CONN_MAX_AGE: 60
      DB_ENGINE: "django.db.backends.mysql"
      DB_HOST: "db"
      DB_NAME: "edx_notes_api"
      DB_PASSWORD: "secret"
      DB_PORT: "3306"
      DB_USER: "notes001"
      ENABLE_DJANGO_TOOLBAR: 1
      ELASTICSEARCH_URL: "http://es:9200"
